# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addRelatedPerson.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(432, 340)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/resources/debt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("")
        Dialog.setModal(True)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, -1, 431, 341))
        self.widget.setStyleSheet("border: 4px solid;\n"
"border-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.1875 rgba(0, 210, 255, 255), stop:1 rgba(0, 255, 173, 255));\n"
"border-radius: 20px;\n"
"background-image: url(:/backgrounds/resources/gradient3.jpg);\n"
"")
        self.widget.setObjectName("widget")
        self.btnAdd = QtWidgets.QPushButton(self.widget)
        self.btnAdd.setGeometry(QtCore.QRect(230, 260, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.btnAdd.setFont(font)
        self.btnAdd.setStyleSheet("background: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.1875 rgba(0, 210, 255, 255), stop:1 rgba(0, 255, 173, 255));\n"
"color: #D9F1F5;\n"
"border:none;\n"
"")
        self.btnAdd.setObjectName("btnAdd")
        self.lblIconAddRelatedPerson = QtWidgets.QLabel(self.widget)
        self.lblIconAddRelatedPerson.setGeometry(QtCore.QRect(160, 30, 111, 111))
        self.lblIconAddRelatedPerson.setStyleSheet("background-image: url();\n"
"background: rgba(0,0,0,0);\n"
"border:none;")
        self.lblIconAddRelatedPerson.setText("")
        self.lblIconAddRelatedPerson.setPixmap(QtGui.QPixmap(":/Icons/resources/add-user.png"))
        self.lblIconAddRelatedPerson.setScaledContents(True)
        self.lblIconAddRelatedPerson.setObjectName("lblIconAddRelatedPerson")
        self.btnCancel = QtWidgets.QPushButton(self.widget)
        self.btnCancel.setGeometry(QtCore.QRect(30, 260, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.btnCancel.setFont(font)
        self.btnCancel.setStyleSheet("background: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.1875 rgba(0, 210, 255, 255), stop:1 rgba(0, 255, 173, 255));\n"
"color: #D9F1F5;\n"
"border:none;\n"
"")
        self.btnCancel.setObjectName("btnCancel")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(60, 170, 321, 41))
        self.widget_2.setStyleSheet("border:none;\n"
"background: rgba(0,0,0,0);")
        self.widget_2.setObjectName("widget_2")
        self.lblIconEdit = QtWidgets.QLabel(self.widget_2)
        self.lblIconEdit.setGeometry(QtCore.QRect(10, 10, 21, 21))
        self.lblIconEdit.setText("")
        self.lblIconEdit.setPixmap(QtGui.QPixmap(":/Icons/resources/edit.png"))
        self.lblIconEdit.setScaledContents(True)
        self.lblIconEdit.setObjectName("lblIconEdit")
        self.lineRelatedPerson = QtWidgets.QLineEdit(self.widget_2)
        self.lineRelatedPerson.setGeometry(QtCore.QRect(0, 0, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineRelatedPerson.setFont(font)
        self.lineRelatedPerson.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineRelatedPerson.setStyleSheet("background-color: #D1F0F3;\n"
"border-radius: 15px;\n"
"padding-left: 35px;\n"
"padding-right: 35px;\n"
"color: #069EAD;")
        self.lineRelatedPerson.setMaxLength(20)
        self.lineRelatedPerson.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineRelatedPerson.setObjectName("lineRelatedPerson")
        self.lineRelatedPerson.raise_()
        self.lblIconEdit.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Warning"))
        self.btnAdd.setText(_translate("Dialog", "ADD"))
        self.btnCancel.setText(_translate("Dialog", "CANCEL"))
        self.lineRelatedPerson.setPlaceholderText(_translate("Dialog", "Name of Related Person"))
import resource_rc
