# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addShopping.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(802, 513)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/resources/debt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("")
        Dialog.setModal(True)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 801, 511))
        self.widget.setStyleSheet("border: 4px solid;\n"
"border-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.1875 rgba(0, 210, 255, 255), stop:1 rgba(0, 255, 173, 255));\n"
"border-radius: 20px;\n"
"background-image: url(:/backgrounds/resources/gradient3.jpg);\n"
"")
        self.widget.setObjectName("widget")
        self.btnAdd = QtWidgets.QPushButton(self.widget)
        self.btnAdd.setGeometry(QtCore.QRect(610, 440, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.btnAdd.setFont(font)
        self.btnAdd.setStyleSheet("background: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.1875 rgba(0, 210, 255, 255), stop:1 rgba(0, 255, 173, 255));\n"
"color: #D9F1F5;\n"
"border:none;\n"
"")
        self.btnAdd.setObjectName("btnAdd")
        self.lblIconAddShopping = QtWidgets.QLabel(self.widget)
        self.lblIconAddShopping.setGeometry(QtCore.QRect(20, 20, 141, 141))
        self.lblIconAddShopping.setStyleSheet("background-image: url();\n"
"background: rgba(0,0,0,0);\n"
"border:none;")
        self.lblIconAddShopping.setText("")
        self.lblIconAddShopping.setPixmap(QtGui.QPixmap(":/Icons/resources/shopping-cart.png"))
        self.lblIconAddShopping.setScaledContents(True)
        self.lblIconAddShopping.setObjectName("lblIconAddShopping")
        self.btnCancel = QtWidgets.QPushButton(self.widget)
        self.btnCancel.setGeometry(QtCore.QRect(430, 440, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.btnCancel.setFont(font)
        self.btnCancel.setStyleSheet("background: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.1875 rgba(0, 210, 255, 255), stop:1 rgba(0, 255, 173, 255));\n"
"color: #D9F1F5;\n"
"border:none;\n"
"")
        self.btnCancel.setObjectName("btnCancel")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(180, 20, 321, 41))
        self.widget_2.setStyleSheet("border:none;\n"
"background: rgba(0,0,0,0);")
        self.widget_2.setObjectName("widget_2")
        self.lineShoppingName = QtWidgets.QLineEdit(self.widget_2)
        self.lineShoppingName.setGeometry(QtCore.QRect(0, 0, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineShoppingName.setFont(font)
        self.lineShoppingName.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineShoppingName.setStyleSheet("background-color: #D1F0F3;\n"
"border-radius: 15px;\n"
"padding-left: 5px;\n"
"color: #069EAD;")
        self.lineShoppingName.setMaxLength(20)
        self.lineShoppingName.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineShoppingName.setObjectName("lineShoppingName")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(180, 70, 321, 41))
        self.widget_3.setStyleSheet("border:none;\n"
"background: rgba(0,0,0,0);")
        self.widget_3.setObjectName("widget_3")
        self.lineShoppingCost = QtWidgets.QLineEdit(self.widget_3)
        self.lineShoppingCost.setGeometry(QtCore.QRect(0, 0, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineShoppingCost.setFont(font)
        self.lineShoppingCost.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineShoppingCost.setStyleSheet("background-color: #D1F0F3;\n"
"border-radius: 15px;\n"
"padding-left: 5px;\n"
"color: #069EAD;")
        self.lineShoppingCost.setMaxLength(20)
        self.lineShoppingCost.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineShoppingCost.setObjectName("lineShoppingCost")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setGeometry(QtCore.QRect(180, 120, 321, 41))
        self.widget_4.setStyleSheet("border:none;\n"
"background: rgba(0,0,0,0);")
        self.widget_4.setObjectName("widget_4")
        self.lineShoppingDate = QtWidgets.QLineEdit(self.widget_4)
        self.lineShoppingDate.setGeometry(QtCore.QRect(0, 0, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineShoppingDate.setFont(font)
        self.lineShoppingDate.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineShoppingDate.setStyleSheet("background-color: #D1F0F3;\n"
"border-radius: 15px;\n"
"padding-left: 5px;\n"
"color: #069EAD;")
        self.lineShoppingDate.setMaxLength(20)
        self.lineShoppingDate.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineShoppingDate.setObjectName("lineShoppingDate")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(30, 180, 741, 191))
        self.scrollArea.setStyleSheet("border:none;\n"
"background: rgba(0,0,0,0);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 741, 191))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.btnAddRelatedPerson = QtWidgets.QPushButton(self.widget)
        self.btnAddRelatedPerson.setGeometry(QtCore.QRect(30, 380, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.btnAddRelatedPerson.setFont(font)
        self.btnAddRelatedPerson.setStyleSheet("background: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.1875 rgba(0, 210, 255, 255), stop:1 rgba(0, 255, 173, 255));\n"
"color: #D9F1F5;\n"
"border:none;\n"
"")
        self.btnAddRelatedPerson.setObjectName("btnAddRelatedPerson")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Warning"))
        self.btnAdd.setText(_translate("Dialog", "ADD"))
        self.btnCancel.setText(_translate("Dialog", "CANCEL"))
        self.lineShoppingName.setPlaceholderText(_translate("Dialog", "Shopping Name"))
        self.lineShoppingCost.setPlaceholderText(_translate("Dialog", "Shopping Cost"))
        self.lineShoppingDate.setPlaceholderText(_translate("Dialog", "Shopping Date"))
        self.btnAddRelatedPerson.setText(_translate("Dialog", "ADD RELATED PERSON"))
import resource_rc
