# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changePassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(421, 458)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/resources/debt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("")
        Dialog.setModal(True)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 421, 231))
        self.widget.setStyleSheet("border: 4px solid;\n"
"border-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.1875 rgba(0, 210, 255, 255), stop:1 rgba(0, 255, 173, 255));\n"
"border-radius: 20px;\n"
"background-image: url(:/backgrounds/resources/gradient3.jpg);\n"
"")
        self.widget.setObjectName("widget")
        self.btnChange = QtWidgets.QPushButton(self.widget)
        self.btnChange.setGeometry(QtCore.QRect(230, 150, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.btnChange.setFont(font)
        self.btnChange.setStyleSheet("background: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.1875 rgba(0, 210, 255, 255), stop:1 rgba(0, 255, 173, 255));\n"
"color: #D9F1F5;\n"
"border:none;\n"
"")
        self.btnChange.setObjectName("btnChange")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(50, 20, 321, 41))
        self.widget_2.setStyleSheet("border:none;\n"
"background: rgba(0,0,0,0);")
        self.widget_2.setObjectName("widget_2")
        self.lblPassIcon = QtWidgets.QLabel(self.widget_2)
        self.lblPassIcon.setGeometry(QtCore.QRect(10, 10, 21, 21))
        self.lblPassIcon.setText("")
        self.lblPassIcon.setPixmap(QtGui.QPixmap(":/Icons/resources/key.png"))
        self.lblPassIcon.setScaledContents(True)
        self.lblPassIcon.setObjectName("lblPassIcon")
        self.btnPassToggle = QtWidgets.QToolButton(self.widget_2)
        self.btnPassToggle.setGeometry(QtCore.QRect(280, 10, 41, 21))
        self.btnPassToggle.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPassToggle.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/resources/eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/Icons/resources/hide.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnPassToggle.setIcon(icon1)
        self.btnPassToggle.setIconSize(QtCore.QSize(30, 30))
        self.btnPassToggle.setCheckable(True)
        self.btnPassToggle.setObjectName("btnPassToggle")
        self.linePassword = QtWidgets.QLineEdit(self.widget_2)
        self.linePassword.setGeometry(QtCore.QRect(0, 0, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.linePassword.setFont(font)
        self.linePassword.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.linePassword.setStyleSheet("background-color: #D1F0F3;\n"
"border-radius: 15px;\n"
"padding-left: 35px;\n"
"padding-right: 35px;\n"
"color: #069EAD;")
        self.linePassword.setMaxLength(20)
        self.linePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.linePassword.setObjectName("linePassword")
        self.linePassword.raise_()
        self.btnPassToggle.raise_()
        self.lblPassIcon.raise_()
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(50, 80, 321, 41))
        self.widget_3.setStyleSheet("border:none;\n"
"background: rgba(0,0,0,0);")
        self.widget_3.setObjectName("widget_3")
        self.lblPassIcon_2 = QtWidgets.QLabel(self.widget_3)
        self.lblPassIcon_2.setGeometry(QtCore.QRect(10, 10, 21, 21))
        self.lblPassIcon_2.setText("")
        self.lblPassIcon_2.setPixmap(QtGui.QPixmap(":/Icons/resources/key.png"))
        self.lblPassIcon_2.setScaledContents(True)
        self.lblPassIcon_2.setObjectName("lblPassIcon_2")
        self.btnPassToggle_2 = QtWidgets.QToolButton(self.widget_3)
        self.btnPassToggle_2.setGeometry(QtCore.QRect(280, 10, 41, 21))
        self.btnPassToggle_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPassToggle_2.setText("")
        self.btnPassToggle_2.setIcon(icon1)
        self.btnPassToggle_2.setIconSize(QtCore.QSize(30, 30))
        self.btnPassToggle_2.setCheckable(True)
        self.btnPassToggle_2.setObjectName("btnPassToggle_2")
        self.linePassword_2 = QtWidgets.QLineEdit(self.widget_3)
        self.linePassword_2.setGeometry(QtCore.QRect(0, 0, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.linePassword_2.setFont(font)
        self.linePassword_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.linePassword_2.setStyleSheet("background-color: #D1F0F3;\n"
"border-radius: 15px;\n"
"padding-left: 35px;\n"
"padding-right: 35px;\n"
"color: #069EAD;")
        self.linePassword_2.setMaxLength(20)
        self.linePassword_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.linePassword_2.setObjectName("linePassword_2")
        self.linePassword_2.raise_()
        self.lblPassIcon_2.raise_()
        self.btnPassToggle_2.raise_()
        self.lblInfo = QtWidgets.QLabel(self.widget)
        self.lblInfo.setGeometry(QtCore.QRect(20, 200, 391, 121))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(22)
        self.lblInfo.setFont(font)
        self.lblInfo.setStyleSheet("color: #D9F1F5;\n"
"background: rgba(0,0,0,0);\n"
"border:none;")
        self.lblInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblInfo.setObjectName("lblInfo")
        self.btnCancel = QtWidgets.QPushButton(self.widget)
        self.btnCancel.setGeometry(QtCore.QRect(20, 150, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.btnCancel.setFont(font)
        self.btnCancel.setStyleSheet("background: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.1875 rgba(0, 210, 255, 255), stop:1 rgba(0, 255, 173, 255));\n"
"color: #D9F1F5;\n"
"border:none;\n"
"")
        self.btnCancel.setObjectName("btnCancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Warning"))
        self.btnChange.setText(_translate("Dialog", "CHANGE"))
        self.linePassword.setPlaceholderText(_translate("Dialog", "Current Password"))
        self.linePassword_2.setPlaceholderText(_translate("Dialog", "New Password"))
        self.lblInfo.setText(_translate("Dialog", "Your password must be  \n"
"at least 8 characters."))
        self.btnCancel.setText(_translate("Dialog", "CANCEL"))
import resource_rc
