# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shoppingInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(681, 421)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/resources/debt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("")
        Dialog.setModal(True)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 681, 421))
        self.widget.setStyleSheet("border: 4px solid;\n"
"border-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.1875 rgba(0, 210, 255, 255), stop:1 rgba(0, 255, 173, 255));\n"
"border-radius: 20px;\n"
"background-image: url(:/backgrounds/resources/gradient3.jpg);\n"
"")
        self.widget.setObjectName("widget")
        self.btnOk = QtWidgets.QPushButton(self.widget)
        self.btnOk.setGeometry(QtCore.QRect(250, 350, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.btnOk.setFont(font)
        self.btnOk.setStyleSheet("background: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.1875 rgba(0, 210, 255, 255), stop:1 rgba(0, 255, 173, 255));\n"
"color: #D9F1F5;\n"
"border:none;\n"
"")
        self.btnOk.setObjectName("btnOk")
        self.lblIconInfo = QtWidgets.QLabel(self.widget)
        self.lblIconInfo.setGeometry(QtCore.QRect(0, 30, 121, 111))
        self.lblIconInfo.setStyleSheet("background-image: url();\n"
"background: rgba(0,0,0,0);\n"
"border:none;")
        self.lblIconInfo.setText("")
        self.lblIconInfo.setPixmap(QtGui.QPixmap(":/Icons/resources/information.png"))
        self.lblIconInfo.setScaledContents(True)
        self.lblIconInfo.setObjectName("lblIconInfo")
        self.lblShoppingName = QtWidgets.QLabel(self.widget)
        self.lblShoppingName.setGeometry(QtCore.QRect(120, 30, 521, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(22)
        self.lblShoppingName.setFont(font)
        self.lblShoppingName.setStyleSheet("color: #D9F1F5;\n"
"background: rgba(0,0,0,0);\n"
"border:none;")
        self.lblShoppingName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblShoppingName.setObjectName("lblShoppingName")
        self.lblShoppingCost = QtWidgets.QLabel(self.widget)
        self.lblShoppingCost.setGeometry(QtCore.QRect(120, 70, 521, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(22)
        self.lblShoppingCost.setFont(font)
        self.lblShoppingCost.setStyleSheet("color: #D9F1F5;\n"
"background: rgba(0,0,0,0);\n"
"border:none;")
        self.lblShoppingCost.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblShoppingCost.setObjectName("lblShoppingCost")
        self.lblShoppingDate = QtWidgets.QLabel(self.widget)
        self.lblShoppingDate.setGeometry(QtCore.QRect(120, 110, 521, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(22)
        self.lblShoppingDate.setFont(font)
        self.lblShoppingDate.setStyleSheet("color: #D9F1F5;\n"
"background: rgba(0,0,0,0);\n"
"border:none;")
        self.lblShoppingDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblShoppingDate.setObjectName("lblShoppingDate")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(40, 160, 601, 171))
        self.scrollArea.setStyleSheet("border:none;\n"
"background: rgba(0,0,0,0);\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 601, 171))
        self.scrollAreaWidgetContents.setStyleSheet("QScrollBar {background: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0.1875 rgba(0, 210, 255, 255), stop:1 rgba(0, 255, 173, 255));}\n"
"QScrollBar::handle:vertical {background:none;}\n"
"QScrollBar::add-line:vertical {background: none;}\n"
"QScrollBar::sub-line:vertical {background: none;}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Warning"))
        self.btnOk.setText(_translate("Dialog", "OK"))
        self.lblShoppingName.setText(_translate("Dialog", "Shopping Name:"))
        self.lblShoppingCost.setText(_translate("Dialog", "Shopping Cost:"))
        self.lblShoppingDate.setText(_translate("Dialog", "Shopping Date:"))
import resource_rc
